### ISSUE TITLE
Not loading CSS file

### ISSUE THREAD

**Issue by selfagency** [dimelo/emojione-rails#2]
Hi,

I followed the usage instructions in the README and added `@import "emojione";` to my application.css.scss file, but there is no line in my rendered HTML code invoking emojione's css file and I get no errors from Ruby that the file can't be found. In fact, if I change it to `@import "/assets/emojione";`, then it throws an error.

I added `//= require emojione` to my application.js file and the line invoking that script appears in my code just fine.

``` HTML
  <script src="/assets/emojione.js?body=1" type="text/javascript"></script>
```

I've also added the jQuery conversion class found [here](http://git.emojione.com/demos/1.5.0/class-convert.html) to my global.js...

``` javascript
     $(document).ready(function() {
        $(".convert-emoji").each(function() {
            var original = $(this).html();
            // use .shortnameToImage if only converting shortnames (for slightly better performance)
            var converted = emojione.toImage(original);
            $(this).html(converted);
        });
    });
```

...but nothing seems to be happening to convert shortcodes within HTML elements that have the `.convert-emoji` class.

Am I doing something wrong or is there a bug w/ your port of Emojione?

**Comment by nel** [comment]
Well this is a emojione question not really a question about this gem. But I tested your snippet with "body" instead and ... this works, for utf8 emojis at least.

So I don't know what to say, if you don't have something like "Uncaught ReferenceError: emojione is not defined" therefore the bug is not in this gem.

**Comment by selfagency** [comment]
Even though the link to the CSS isn't loading?

**Comment by nel** [comment]
First of all Emojione does not require any css to work (unless you want to use the png sprite which not supported by this gem and IMHO a very bad idea in general). The css is just so that images fallback are display nicely but they will be displayed anyway.

Emojione is mostly js, and if you have the emojione global in your js then you have emojione working.

The only difficulty with emojione is the image path as emojione actually rely on img tag pointing to the emojis in png or svg. That's why I provided a rake task for you to copy them.

But here again at worse you will have 404 imgs but the js part will work.

Your @import "/assets/emojione"; SHOULD NOT work as the css is in the gem not your project, I invite you to read a bit more about spockets if you have trouble understanding the difference between @import "emojione" that will load ANY emojione css/scss in the path (including the gem) and @import "/assets/emojione"; that will try in your OWN project to find a file located at an absolute position (that does not exist by the way).

So the problem is most probably that you don't have a .convert-emoji class in your html ?

**Comment by selfagency** [comment]
Nel, thanks for your explanation. I guess I am confused as to why you instruct users to add `@import "emojione";` to their application.css.scss file if there's nothing to be loaded. I did have a `.convert-emoji` class in my HTML, but even with it switched to `body`, the JS simply isn't executing, and I'm at a loss to explain why.

**Comment by nel** [comment]
There is something loaded, https://github.com/dimelo/emojione-rails/blob/master/app/assets/css/emojione.css is loaded but this css is just for rendering, this does not prevent the js to work or not.

**Comment by selfagency** [comment]
Thanks for your help. I've moved the issue here. https://github.com/Ranks/emojione/issues/130
